"""Generate docs/data_dictionary.md from the feature registry and the live database schema."""
from __future__ import annotations

import warnings

warnings.filterwarnings("ignore")

from common.config import ROOT
from common.db import read_sql
from ml.feature_engineering import FEATURES

TABLES = {
    "raw_application": "Loan Origination System — one row per applicant (booked portfolio + recent intake).",
    "raw_bureau": "Credit Bureau — external credit accounts reported for the applicant.",
    "raw_bureau_balance": "Credit Bureau — monthly status (DPD bucket) per bureau account.",
    "raw_previous_application": "Previous Loan System — prior applications with the lender.",
    "raw_installments": "Payment System — instalments due and payments made on previous loans.",
    "raw_pos_cash": "POS / Cash Loan System — monthly balance snapshots.",
    "raw_credit_card": "Credit Card System — monthly card balance, limit, drawings, DPD.",
    "customer_360": "Consolidated customer profile + engineered features (sql/customer_360.sql).",
    "customer_behaviour_monthly": "Customer × month behaviour fact (months -24..-1) for trend analytics.",
    "risk_scores": "Risk engine output: PD, challenger PD, risk score, tier, LGD, EAD, Expected Loss.",
    "customer_explanations": "Top-5 risk-increasing / decreasing SHAP drivers per customer.",
    "global_feature_importance": "Mean absolute SHAP value per feature and population.",
    "early_warning_signals": "Early Warning Score, band and top trigger per customer.",
    "ews_triggers": "Every early-warning trigger fired, with severity and evidence.",
    "anomaly_scores": "Isolation Forest percentile, rule score, anomaly score and status.",
    "anomaly_rules": "Every anomaly rule fired, with evidence.",
    "model_registry": "Model versions, roles, features, hyper-parameters, test metrics, curves.",
    "model_monitoring": "Monitoring runs: feature/score PSI, segment drift, performance stability.",
    "data_quality_checks": "Data-quality check results per ETL run.",
    "etl_runs": "ETL run metadata (row counts, cleaning log).",
    "audit_log": "Audit trail: AI queries, tool calls, responses, investigations, scoring, model events.",
}


def main() -> None:
    cols = read_sql("""SELECT table_name, COUNT(*) AS n FROM information_schema.columns
                       WHERE table_schema='public' GROUP BY 1""").set_index("table_name").n.to_dict()
    rows = read_sql("""SELECT relname, n_live_tup FROM pg_stat_user_tables""").set_index("relname").n_live_tup.to_dict()
    out = ["# Data Dictionary", "",
           "_Generated by `python -m scripts.generate_data_dictionary` from the live schema and the feature registry._", "",
           "## Tables", "", "| Table | Columns | Rows (approx.) | Description |", "|---|---|---|---|"]
    for t, d in TABLES.items():
        out.append(f"| `{t}` | {cols.get(t, '—')} | {rows.get(t, 0):,} | {d} |")
    out += ["", "Views: `v_portfolio` (one analytical row per customer joining Customer 360 + risk + EWS + anomaly), "
            "`v_portfolio_by_vintage`, `v_investigation_queue` (priority-ranked), materialized `mv_behaviour_trend`.",
            "", "## Business dimensions (Customer 360)", "",
            "| Dimension | Definition |", "|---|---|",
            "| `vintage` | SIMULATED booking quarter: booked applicants ordered by SK_ID_CURR and split into 8 equal quarters (2024-Q1…2025-Q4); intake = 2026-Q1. Source has no calendar dates. |",
            "| `product` | NAME_CONTRACT_TYPE (Cash loans / Revolving loans) |",
            "| `region` | 'Region Tier n' from REGION_RATING_CLIENT_W_CITY (1 best – 3 worst) |",
            "| `income_band` | AMT_INCOME_TOTAL bands: <100K, 100K–150K, 150K–225K, 225K–300K, 300K+ |",
            "| `customer_segment` | NAME_INCOME_TYPE grouped: Working, Commercial associate, Pensioner, State servant, Other |",
            "| `credit_score_band` | average of EXT_SOURCE_1-3: A ≥0.65, B ≥0.55, C ≥0.45, D ≥0.35, E <0.35, Unscored |",
            "| `default_flag` | OBSERVED outcome = Home Credit TARGET (payment difficulties); NULL for intake |",
            "", "## Model features", "", "| Feature | Business label | Source system | Unit |", "|---|---|---|---|"]
    for f, (label, group, unit) in FEATURES.items():
        out.append(f"| `{f}` | {label} | {group} | {unit} |")
    out += ["", "## Cleaning rules", "",
            "- `DAYS_EMPLOYED = 365243` (pensioner/unemployed sentinel) → NULL, flagged in `not_employed_flag`.",
            "- `CODE_GENDER = 'XNA'` → NULL. Previous-application `DAYS_* = 365243` sentinels → NULL.",
            "- Exact duplicate rows dropped; column names normalised to snake_case.",
            "- Leakage guard: only behaviour dated before the application (`DAYS_* < 0`, `MONTHS_BALANCE < 0`)."]
    (ROOT / "docs" / "data_dictionary.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("wrote docs/data_dictionary.md")


if __name__ == "__main__":
    main()
