"""
Step 4 — Load into PostgreSQL.

Raw-layer DDL is generated from the cleaned DataFrames (column types inferred
from pandas dtypes) and written to sql/schema_raw.sql so the physical schema
is always inspectable. Data is bulk-loaded with COPY (fast, streaming).
"""
from __future__ import annotations

import io
import logging

import pandas as pd

from common.config import ROOT
from common.db import get_engine

log = logging.getLogger("risklens.etl")

RAW_INDEXES = {
    "raw_application": ["sk_id_curr", "customer_id", "population"],
    "raw_bureau": ["sk_id_curr", "sk_id_bureau"],
    "raw_bureau_balance": ["sk_id_bureau", "months_balance"],
    "raw_previous_application": ["sk_id_curr", "sk_id_prev", "days_decision"],
    "raw_installments": ["sk_id_curr", "sk_id_prev", "days_instalment"],
    "raw_pos_cash": ["sk_id_curr", "sk_id_prev", "months_balance"],
    "raw_credit_card": ["sk_id_curr", "sk_id_prev", "months_balance"],
}
PRIMARY_KEYS = {
    "raw_application": "sk_id_curr",
    "raw_bureau": "sk_id_bureau",
    "raw_previous_application": "sk_id_prev",
}


def _pg_type(dtype) -> str:
    s = str(dtype)
    if s in ("int64", "Int64", "int32", "Int32", "int8", "int16"):
        return "BIGINT"
    if s.startswith("float"):
        return "DOUBLE PRECISION"
    if s == "bool":
        return "BOOLEAN"
    return "TEXT"


def _normalise_ints(df: pd.DataFrame) -> pd.DataFrame:
    """Float columns that only contain whole numbers (pandas upcasts ints with NaN) -> Int64."""
    for c in df.columns:
        if str(df[c].dtype).startswith("float"):
            s = df[c].dropna()
            if len(s) and (s % 1 == 0).all() and (c.startswith(("cnt_", "sk_", "flag_", "days_", "months_",
                                                                  "num_", "hour_", "region_rating", "nflag_",
                                                                  "def_", "obs_", "target", "sellerplace"))):
                df[c] = df[c].astype("Int64")
    return df


def ddl_for(table: str, df: pd.DataFrame) -> str:
    cols = []
    for c in df.columns:
        t = _pg_type(df[c].dtype)
        nn = " NOT NULL" if PRIMARY_KEYS.get(table) == c else ""
        cols.append(f'    "{c}" {t}{nn}')
    pk = PRIMARY_KEYS.get(table)
    if pk:
        cols.append(f"    PRIMARY KEY ({pk})")
    idx = "\n".join(f"CREATE INDEX IF NOT EXISTS ix_{table}_{c} ON {table} ({c});"
                    for c in RAW_INDEXES.get(table, []) if c != pk)
    return f"DROP TABLE IF EXISTS {table} CASCADE;\nCREATE TABLE {table} (\n" + ",\n".join(cols) + "\n);\n" + idx + "\n"


def copy_frame(table: str, df: pd.DataFrame, chunk: int = 500_000) -> None:
    raw = get_engine().raw_connection()
    try:
        with raw.cursor() as cur:
            cols = ", ".join(f'"{c}"' for c in df.columns)
            for start in range(0, len(df), chunk):
                buf = io.StringIO()
                df.iloc[start:start + chunk].to_csv(buf, index=False, header=False, na_rep="\\N")
                buf.seek(0)
                with cur.copy(f"COPY {table} ({cols}) FROM STDIN WITH (FORMAT csv, NULL '\\N')") as cp:
                    while data := buf.read(1 << 20):
                        cp.write(data)
        raw.commit()
    finally:
        raw.close()


def load_raw(tables: dict[str, pd.DataFrame]) -> None:
    ddl_all = ["-- AUTO-GENERATED by etl/load_postgres.py from the cleaned source data.",
               "-- Raw layer: one table per source system.\n"]
    raw = get_engine().raw_connection()
    try:
        for name, df in tables.items():
            df = _normalise_ints(df)
            tables[name] = df
            ddl = ddl_for(name, df)
            ddl_all.append(ddl)
            # create table first, indexes after load (faster)
            create, _, index_sql = ddl.partition(");\n")
            with raw.cursor() as cur:
                cur.execute(create + ");")
            raw.commit()
            copy_frame(name, df)
            with raw.cursor() as cur:
                if index_sql.strip():
                    cur.execute(index_sql)
                cur.execute(f"ANALYZE {name};")
            raw.commit()
            log.info("loaded %-26s %10s rows", name, f"{len(df):,}")
    finally:
        raw.close()
    (ROOT / "sql" / "schema_raw.sql").write_text("\n".join(ddl_all), encoding="utf-8")


def load_frame(table: str, df: pd.DataFrame, if_exists: str = "replace") -> None:
    """Generic loader for analytical/operational tables produced in Python."""
    df.to_sql(table, get_engine(), if_exists=if_exists, index=False, method="multi", chunksize=5000)
