-- =====================================================================
-- RiskLens — operational & analytical schema
-- (Raw source-system tables are generated by the ETL: see schema_raw.sql)
-- =====================================================================

-- ---------- Pipeline / governance ------------------------------------
CREATE TABLE IF NOT EXISTS etl_runs (
    run_id          TEXT PRIMARY KEY,
    started_at      TIMESTAMPTZ NOT NULL,
    finished_at     TIMESTAMPTZ,
    status          TEXT NOT NULL,
    sample_portfolio INT,
    sample_intake   INT,
    row_counts      JSONB,
    cleaning_log    JSONB
);

CREATE TABLE IF NOT EXISTS data_quality_checks (
    run_id        TEXT NOT NULL,
    run_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    table_name    TEXT NOT NULL,
    check_name    TEXT NOT NULL,
    category      TEXT NOT NULL,
    metric_value  DOUBLE PRECISION,
    threshold     TEXT,
    status        TEXT NOT NULL CHECK (status IN ('PASS','WARN','FAIL')),
    detail        TEXT
);
CREATE INDEX IF NOT EXISTS ix_dq_run ON data_quality_checks (run_id);

-- ---------- Model governance -----------------------------------------
CREATE TABLE IF NOT EXISTS model_registry (
    model_name     TEXT NOT NULL,
    model_version  TEXT NOT NULL,
    role           TEXT NOT NULL CHECK (role IN ('champion','challenger')),
    algorithm      TEXT NOT NULL,
    training_date  TIMESTAMPTZ NOT NULL,
    features       JSONB NOT NULL,
    hyperparameters JSONB,
    metrics        JSONB NOT NULL,     -- evaluated on held-out test split
    curves         JSONB,              -- ROC / calibration points for the UI
    train_rows     INT,
    test_rows      INT,
    artifact_path  TEXT NOT NULL,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (model_name, model_version)
);

-- ---------- Risk engine outputs --------------------------------------
CREATE TABLE IF NOT EXISTS risk_scores (
    sk_id_curr     BIGINT PRIMARY KEY,
    customer_id    TEXT NOT NULL,
    model_name     TEXT NOT NULL,
    model_version  TEXT NOT NULL,
    pd             DOUBLE PRECISION NOT NULL,   -- model prediction
    pd_challenger  DOUBLE PRECISION,
    risk_score     INT NOT NULL,                -- 0-100 PD percentile vs development population
    risk_tier      TEXT NOT NULL,
    lgd            DOUBLE PRECISION NOT NULL,   -- ASSUMPTION (config.LGD_ASSUMPTIONS)
    ead            DOUBLE PRECISION NOT NULL,   -- derived (credit amount, CCF for revolving)
    expected_loss  DOUBLE PRECISION NOT NULL,   -- PD x LGD x EAD
    dataset_split  TEXT NOT NULL,               -- train / valid / test / intake
    scored_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_rs_tier ON risk_scores (risk_tier);
CREATE INDEX IF NOT EXISTS ix_rs_customer ON risk_scores (customer_id);

CREATE TABLE IF NOT EXISTS customer_explanations (
    sk_id_curr     BIGINT NOT NULL,
    rank           INT NOT NULL,
    feature        TEXT NOT NULL,
    feature_value  DOUBLE PRECISION,
    shap_value     DOUBLE PRECISION NOT NULL,   -- contribution to log-odds of default
    direction      TEXT NOT NULL CHECK (direction IN ('increases_risk','decreases_risk')),
    PRIMARY KEY (sk_id_curr, rank)
);

CREATE TABLE IF NOT EXISTS global_feature_importance (
    model_name   TEXT NOT NULL,
    model_version TEXT NOT NULL,
    population   TEXT NOT NULL,
    feature      TEXT NOT NULL,
    mean_abs_shap DOUBLE PRECISION NOT NULL,
    mean_shap    DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (model_name, model_version, population, feature)
);

CREATE TABLE IF NOT EXISTS early_warning_signals (
    sk_id_curr   BIGINT PRIMARY KEY,
    ews_score    INT NOT NULL,
    ews_band     TEXT NOT NULL,
    n_triggers   INT NOT NULL,
    top_trigger  TEXT,
    top_severity TEXT
);
CREATE INDEX IF NOT EXISTS ix_ews_band ON early_warning_signals (ews_band);

CREATE TABLE IF NOT EXISTS ews_triggers (
    sk_id_curr   BIGINT NOT NULL,
    trigger_code TEXT NOT NULL,
    severity     TEXT NOT NULL,
    description  TEXT NOT NULL,
    evidence     TEXT NOT NULL,
    PRIMARY KEY (sk_id_curr, trigger_code)
);
CREATE INDEX IF NOT EXISTS ix_ewst_code ON ews_triggers (trigger_code);

CREATE TABLE IF NOT EXISTS anomaly_scores (
    sk_id_curr      BIGINT PRIMARY KEY,
    isolation_raw   DOUBLE PRECISION NOT NULL,
    isolation_pct   DOUBLE PRECISION NOT NULL,
    rule_score      DOUBLE PRECISION NOT NULL,
    anomaly_score   INT NOT NULL,
    anomaly_status  TEXT NOT NULL,
    n_rules         INT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_anom_status ON anomaly_scores (anomaly_status);

CREATE TABLE IF NOT EXISTS anomaly_rules (
    sk_id_curr   BIGINT NOT NULL,
    rule_code    TEXT NOT NULL,
    description  TEXT NOT NULL,
    evidence     TEXT NOT NULL,
    PRIMARY KEY (sk_id_curr, rule_code)
);

-- ---------- Monitoring -----------------------------------------------
CREATE TABLE IF NOT EXISTS model_monitoring (
    run_id        TEXT NOT NULL,
    run_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    model_name    TEXT NOT NULL,
    model_version TEXT NOT NULL,
    metric_type   TEXT NOT NULL,     -- feature_psi / score_psi / segment_mix / performance
    subject       TEXT NOT NULL,     -- feature or segment name
    baseline      TEXT,
    comparison    TEXT,
    value         DOUBLE PRECISION,
    status        TEXT,              -- Stable / Warning / Critical
    detail        JSONB
);
CREATE INDEX IF NOT EXISTS ix_mon_run ON model_monitoring (run_id, metric_type);

-- ---------- Audit trail ----------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id            BIGSERIAL PRIMARY KEY,
    ts            TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_name     TEXT NOT NULL DEFAULT 'analyst',
    session_id    TEXT,
    action        TEXT NOT NULL,     -- ai_query / tool_call / ai_response / investigation_opened / risk_scoring / model_registered
    tool          TEXT,
    customer_id   TEXT,
    parameters    JSONB,
    result_summary TEXT,
    status        TEXT DEFAULT 'ok'
);
CREATE INDEX IF NOT EXISTS ix_audit_ts ON audit_log (ts DESC);
CREATE INDEX IF NOT EXISTS ix_audit_customer ON audit_log (customer_id);
